apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-service
  namespace: pycon-pulse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-service
  template:
    metadata:
      labels:
        app: api-service
    spec:
      containers:
      - name: api-service
        image: pycon-pulse/api-service:latest
        imagePullPolicy: Never  # Use local image
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: app-config
        - secretRef:
            name: app-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: pycon-pulse
spec:
  type: NodePort
  selector:
    app: api-service
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30800
