apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-analysis-service
  namespace: pycon-pulse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-analysis-service
  template:
    metadata:
      labels:
        app: ai-analysis-service
    spec:
      containers:
      - name: ai-analysis-service
        image: pycon-pulse/ai-analysis-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8001
        envFrom:
        - configMapRef:
            name: app-config
        - secretRef:
            name: app-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: ai-analysis-service
  namespace: pycon-pulse
spec:
  selector:
    app: ai-analysis-service
  ports:
  - port: 8001
    targetPort: 8001
