apiVersion: batch/v1
kind: CronJob
metadata:
  name: collector-service
  namespace: pycon-pulse
spec:
  schedule: "*/30 * * * *"  # Every 30 minutes
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: collector
            image: pycon-pulse/collector-service:latest
            imagePullPolicy: Never
            envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secrets
---
# Also create a one-time Job to run immediately
apiVersion: batch/v1
kind: Job
metadata:
  name: collector-initial-run
  namespace: pycon-pulse
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: collector
        image: pycon-pulse/collector-service:latest
        imagePullPolicy: Never
        envFrom:
        - configMapRef:
            name: app-config
        - secretRef:
            name: app-secrets
